FROM python:3.10.6-bullseye

RUN pip3 install --upgrade pip \
  && pip3 install mkdocs mkdocs-material fontawesome-markdown python-markdown-math pygments pymdown-extensions
RUN pip3 install mkdocs-github-admonitions-plugin mdx_truly_sane_lists