name: Deploy to EC2

on:
  push

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_NAME }}
        username: ${{ secrets.EC2_USER_NAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd pages-test/
          git fetch
          git checkout -b ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}
          cd .devcontainer
          docker compose run dev mkdocs build
          cd ~/
          rm -rf repos/pages-test/${{ github.ref_name }}
          cp -r pages-test/site repos/pages-test/${{ github.ref_name }}
