name: ci 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.12
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - run: pip install mkdocs mkdocs-material fontawesome-markdown python-markdown-math pygments pymdown-extensions mkdocs-github-admonitions-plugin mdx_truly_sane_lists
      - run: mkdocs gh-deploy --force